# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a34fbe593806d8e7c1a1c82dcadbf17d09c4d29a1e3431ebdf117479c90995a4ad5cf5a83a84ece372187b50c71ee3d7aa6ffffa9edc2cfeee423d15aee0dc1d

test:
  secret_key_base: 3cba70014ae25c2a2b3e2fbaa33f867838f1f79c691f997c35dd3eba976c36c25415071470e7708c9aaa1fb9c13684bc0150eb4f144f344bb982436f9451844f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
