# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21ddcf889dd33e25f01f3da56294352270bff2cf32cbd575ebbc8fcb2a7e53e5986594d393b47106b0e1f56f981ab075ea68ee121e403d08392e410afa7c74a8

test:
  secret_key_base: 4dba893f9d6be0adb223a3896ee67b0a31e7ebce6600f79e45d3d8115312bd5e5f51ebd8f64cd8e8eea85370fcacf32d0f3ce6ea30663a1684b7677803812782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
